package com.leandromendes.aidl_interface;

import static java.lang.String.format;

import android.content.ComponentName;
import android.content.Context;
import android.content.Intent;
import android.content.ServiceConnection;
import android.os.Bundle;
import android.os.IBinder;
import android.os.RemoteException;
import android.util.Log;
import android.widget.Button;
import android.widget.TextView;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;

public class MainActivity extends AppCompatActivity {
    private IRandomKey randomKeyService;
    private boolean isConnected = false;
    private Button generate;
    private TextView keyDisplay;
    private static final String TAG = "MainActivity";

    private ServiceConnection serviceConnection = new ServiceConnection() {
        @Override
        public void onServiceConnected(ComponentName name, IBinder service) {
            randomKeyService = IRandomKey.Stub.asInterface(service);
            isConnected = true;
            Log.d(TAG, "Service successfully connected!");
        }

        @Override
        public void onServiceDisconnected(ComponentName name) {
            isConnected = false;
            randomKeyService = null;
            Log.d(TAG, "Service disconnected!");
        }
    };

    /*
    * Returns a random key generated by the service if it is connected.
    * Otherwise, it returns 0
    * */
    private int generateKey() {
        if(isConnected){
            try {
               return randomKeyService.getRandomKey();
            }
            catch (RemoteException e) {
                e.printStackTrace();
            }
        }
        Log.d(TAG, "The service is not yet available!");
        return 0;
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_main);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        // Create an intent for a specific component
        // Create intent
        Intent intent = new Intent();
        // Define the component
        intent.setComponent(
                new ComponentName(
                        "com.leandromendes.aidl_interface",
                        "com.leandromendes.aidl_interface.RandomKey"));

        // Connect the binder to the service
        bindService(intent, serviceConnection, Context.BIND_AUTO_CREATE);

        generate = findViewById(R.id.GenerateButton);
        keyDisplay = findViewById(R.id.KeyDisplay);

        generate.setOnClickListener(v -> {
            keyDisplay.setText(format("%d", generateKey()));
        });
    }

    @Override
    protected void onResume(){
        super.onResume();
        keyDisplay.setText(format("%d", generateKey()));
    }

    @Override
    protected void onDestroy(){
        super.onDestroy();
        if (isConnected) {
            unbindService(serviceConnection);
            isConnected = false;
        }
    }

}